export const STARTED_GETTING_UTILITIES = 'ERROR_GETTING_UTILITIES';
export const FINISHED_GETTING_UTILITIES = 'FINISHED_GETTING_UTILITIES';
export const ERROR_GETTING_UTILITIES = 'ERROR_GETTING_UTILITIES';
