export const STARTED_GETTING_UTILITIES = 'ERROR_GETTING_UTILITIES';
export const FINISHED_GETTING_UTILITIES = 'FINISHED_GETTING_UTILITIES';
export const ERROR_GETTING_UTILITIES = 'ERROR_GETTING_UTILITIES';
export const STARTED_GETTING_LOCATION = 'STARTED_GETTING_LOCATION';
export const FINISHED_GETTING_LOCATION = 'FINISHED_GETTING_LOCATION';
export const ERROR_GETTING_LOCATION = 'ERROR_GETTING_LOCATION';
